server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://auth-service:8081}
              predicates:
                - Path=/api/auth/**

            - id: task-service
              uri: ${TASK_SERVICE_URL:http://task-service:8082}
              predicates:
                - Path=/api/tasks/**
            # =========================
            # AI ASSISTANT SERVICE
            # =========================
            - id: ai-assistant-service
              uri: ${AI_ASSISTANT_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/api/ai/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:4200"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
